const types = {
    //global
    TOGGLE_LOADING: 'TOGGLE_LOADING',
    TOGGLE_MENU: 'TOGGLE_MENU',
    HIDDEN_MENU: 'HIDDEN_MENU',

    //login
    GET_ADMININFO: 'GET_ADMIN',
    ADMIN_LOGIN: 'ADMIN_LOGIN',
    ADMIN_REGISTER: 'ADMIN_REGISTER',
    ADMIN_LOGINOUT: 'ADMIN_LOGINOUT',

    //router
    SET_ROUTER: 'SET_ROUTER',

    //todoitem
    ADD_TODOITEM: 'ADD_TODOITEM',
    DELETE_TODOITEM: 'DELETE_TODOITEM',
    TOGGLE_TODOITEM: 'TOGGLE_TODOITEM',

    //admin
    GET_ADMINLIST: 'GET_ADMINLIST',
    ADD_ADMIN: 'ADD_ADMIN',
    GET_ALLADMINUSERNAME: 'GET_ALLADMINUSERNAME',

    //user
    GET_USERLIST: 'GET_USERLIST',

    //readingArticle
    GET_READINGARTICLELIST: 'GET_READINGARTICLELIST',

    //musicArticle
    GET_MUSICARTICLELIST: 'GET_MUSICARTICLELIST',

    //filmArticle
    GET_FILMARTICLELIST: 'GET_FILMARTICLELIST',

    //SoundArticle
    GET_SOUNDARTICLELIST: 'GET_SOUNDARTICLELIST'
}

export default types
